version: "3.1"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    volumes:
      - /sessions
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      
  # postgres:
  #   container_name: postgres
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_USER: alex
  #     POSTGRES_PASSWORD: 123
  #   volumes:
  #     - ./pg_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: always

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
