version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin_nest
    image: phpmyadmin
    restart: always
    volumes:
      - /sessions
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
