version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 123
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
